### ISSUE TITLE
500 Internal Server Error プロセス実行中にタイムアウト

### ISSUE THREAD

**Issue by Takesikaityo** [tomocrafter/PEQueries#1]
<img src="https://lh3.googleusercontent.com/-03TlcYDCQIQ/WS_Qib4r8uI/AAAAAAAARxw/H_qBtuLHdTI4VzY0jmR27V8g5WE-T-JdgCL0B/w530-d-h136-p-rw/%25E3%2582%25AD%25E3%2583%25A3%25E3%2583%2597%25E3%2583%2581%25E3%2583%25A3.PNG">

CGI実行エラー : プロセス実行中にタイムアウトしました
詳細情報はありません。
サンプルの通りにしたのですが、

環境：
OS :: Microsoft Windows 10 Home Insider Preview (10.0.16199) 64bit
PHP Version 7.1.1
Architecture x86

**Comment by tomocrafter** [comment]
ご報告ありがとうございます。
可能でしたら
```php
error_reporting(-1);
ini_set('display_errors', 1);
```
というコードをサンプルに記入の上でエラーを掲示していただけたら幸いです。

thanks for report!
